# Generated by Django 4.0.5 on 2022-07-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generator',
            new_name='Author',
        ),
    ]
