# Generated by Django 4.0.5 on 2022-07-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_generator_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Rule',
        ),
    ]
