# Generated by Django 4.0.5 on 2022-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rules', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='rule/images/')),
            ],
        ),
    ]
